openapi: 3.0.1
info:
  title: Process Text API
  description: API for processing text inputs.
  version: 1.0.0
servers:
  - url: https://us-central1-agentbuilderhackathon.cloudfunctions.net/
    description: Default server
paths:
  /process_text/echo:
    post:
      summary: Echo the provided text input
      description: This endpoint echoes back the provided text input.
      operationId: echo
      requestBody:
        description: Input text to be processed
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chat:
                  type: string
                  example: "What are the issue types with maximum number of tickets from 16th to 19th April?"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  chat:
                    type: string
                    example: "What are the issue types with maximum number of tickets from 16th to 19th April?"
